<?php
$dalTablepad_pemda = array();
$dalTablepad_pemda["id"] = array("type"=>3,"varname"=>"id");
$dalTablepad_pemda["type"] = array("type"=>200,"varname"=>"type");
$dalTablepad_pemda["kepala_nama"] = array("type"=>200,"varname"=>"kepala_nama");
$dalTablepad_pemda["alamat"] = array("type"=>200,"varname"=>"alamat");
$dalTablepad_pemda["telp"] = array("type"=>200,"varname"=>"telp");
$dalTablepad_pemda["pemda_nama"] = array("type"=>200,"varname"=>"pemda_nama");
$dalTablepad_pemda["ibukota"] = array("type"=>200,"varname"=>"ibukota");
$dalTablepad_pemda["tmt"] = array("type"=>135,"varname"=>"tmt");
$dalTablepad_pemda["jabatan"] = array("type"=>200,"varname"=>"jabatan");
$dalTablepad_pemda["ppkd_id"] = array("type"=>20,"varname"=>"ppkd_id");
$dalTablepad_pemda["reklame_id"] = array("type"=>2,"varname"=>"reklame_id");
$dalTablepad_pemda["pendapatan_id"] = array("type"=>3,"varname"=>"pendapatan_id");
$dalTablepad_pemda["pemda_nama_singkat"] = array("type"=>200,"varname"=>"pemda_nama_singkat");
$dalTablepad_pemda["airtanah_id"] = array("type"=>2,"varname"=>"airtanah_id");
$dalTablepad_pemda["self_dok_id"] = array("type"=>3,"varname"=>"self_dok_id");
$dalTablepad_pemda["office_dok_id"] = array("type"=>3,"varname"=>"office_dok_id");
$dalTablepad_pemda["tgl_jatuhtempo_self"] = array("type"=>3,"varname"=>"tgl_jatuhtempo_self");
$dalTablepad_pemda["spt_denda"] = array("type"=>5,"varname"=>"spt_denda");
$dalTablepad_pemda["tgl_spt"] = array("type"=>3,"varname"=>"tgl_spt");
$dalTablepad_pemda["pad_bunga"] = array("type"=>5,"varname"=>"pad_bunga");
$dalTablepad_pemda["fax"] = array("type"=>200,"varname"=>"fax");
$dalTablepad_pemda["website"] = array("type"=>200,"varname"=>"website");
$dalTablepad_pemda["email"] = array("type"=>200,"varname"=>"email");
$dalTablepad_pemda["daerah"] = array("type"=>200,"varname"=>"daerah");
$dalTablepad_pemda["alamat_lengkap"] = array("type"=>200,"varname"=>"alamat_lengkap");
$dalTablepad_pemda["ppj_id"] = array("type"=>2,"varname"=>"ppj_id");
$dalTablepad_pemda["hotel_id"] = array("type"=>2,"varname"=>"hotel_id");
$dalTablepad_pemda["walet_id"] = array("type"=>2,"varname"=>"walet_id");
$dalTablepad_pemda["restauran_id"] = array("type"=>2,"varname"=>"restauran_id");
$dalTablepad_pemda["hiburan_id"] = array("type"=>2,"varname"=>"hiburan_id");
$dalTablepad_pemda["parkir_id"] = array("type"=>2,"varname"=>"parkir_id");
$dalTablepad_pemda["enabled"] = array("type"=>2,"varname"=>"enabled");
$dalTablepad_pemda["surat_no"] = array("type"=>200,"varname"=>"surat_no");
$dalTablepad_pemda["ijin_kd"] = array("type"=>200,"varname"=>"ijin_kd");
$dalTablepad_pemda["hotel_kd"] = array("type"=>200,"varname"=>"hotel_kd");
$dalTablepad_pemda["restoran_kd"] = array("type"=>200,"varname"=>"restoran_kd");
$dalTablepad_pemda["hiburan_kd"] = array("type"=>200,"varname"=>"hiburan_kd");
$dalTablepad_pemda["ppj_kd"] = array("type"=>200,"varname"=>"ppj_kd");
$dalTablepad_pemda["parkir_kd"] = array("type"=>200,"varname"=>"parkir_kd");
$dalTablepad_pemda["airtanah_kd"] = array("type"=>200,"varname"=>"airtanah_kd");
$dalTablepad_pemda["reklame_kd"] = array("type"=>200,"varname"=>"reklame_kd");
$dalTablepad_pemda["restauran_kd"] = array("type"=>200,"varname"=>"restauran_kd");
	$dalTablepad_pemda["id"]["key"]=true;
$dal_info["pad_pemda"]=&$dalTablepad_pemda;

?>